updatePullRequests = "always"

updates.includeScala = true
updates.includeScalaSnapshot = false
updates.pin = [
  { groupId = "org.scala-lang", artifactId = "scala3-library", version = "3.9." },
  { groupId = "org.scala-lang", artifactId = "scala3-compiler", version = "3.9." }
]
