rules = [
  OrganizeImports,
  RemoveUnused,
  RedundantSyntax
]

RemoveUnused.imports = false

OrganizeImports.targetDialect = Scala3
OrganizeImports.groupedImports = Merge
OrganizeImports.groups = [
  "re:peloton\\."
  "*"
  "re:(javax?|scala)\\."
]
