name: Launch Scala Steward

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache:        'sbt'

      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          author-name: Scala Steward
          author-email: ${{ secrets.WORKFLOW_EMAIL }}
          github-token: ${{ secrets.REPO_GITHUB_TOKEN }}
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
