name: Launch ScalaTest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '21'
        cache:        'sbt'

    - name: Run tests
      run: sbt test

    - name: Build artifacts
      run: sbt assembly
